//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EffortEstimationExcelEngine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EffortEstEntities : DbContext
    {
        public EffortEstEntities()
            : base("name=EffortEstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblScrumTeam> tblScrumTeams { get; set; }
    
        public virtual ObjectResult<Act_19_Result> Act_19(string sV_SalaryId, string month)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Act_19_Result>("Act_19", sV_SalaryIdParameter, monthParameter);
        }
    
        public virtual ObjectResult<ActDec_18_Result> ActDec_18(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActDec_18_Result>("ActDec_18", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<ActFeb_19_Result> ActFeb_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActFeb_19_Result>("ActFeb_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<ActJan_19_Result> ActJan_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActJan_19_Result>("ActJan_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<ActMar_19_Result> ActMar_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActMar_19_Result>("ActMar_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<ActNov_18_Result> ActNov_18(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ActNov_18_Result>("ActNov_18", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<string> ForcFeb_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ForcFeb_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<string> ForcJan_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ForcJan_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<string> ForcMar_19(string sV_SalaryId)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ForcMar_19", sV_SalaryIdParameter);
        }
    
        public virtual ObjectResult<SP_Act_19_Result> SP_Act_19(string sV_SalaryId, string month)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Act_19_Result>("SP_Act_19", sV_SalaryIdParameter, monthParameter);
        }
    
        public virtual ObjectResult<SP_Forec_19_Result> SP_Forec_19(string sV_SalaryId, string month)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Forec_19_Result>("SP_Forec_19", sV_SalaryIdParameter, monthParameter);
        }
    
        public virtual ObjectResult<SP_Forec_191_Result> SP_Forec_191(string sV_SalaryId, string month)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Forec_191_Result>("SP_Forec_191", sV_SalaryIdParameter, monthParameter);
        }
    
        public virtual ObjectResult<SP_Forecast_19_Result> SP_Forecast_19(string sV_SalaryId, string month)
        {
            var sV_SalaryIdParameter = sV_SalaryId != null ?
                new ObjectParameter("SV_SalaryId", sV_SalaryId) :
                new ObjectParameter("SV_SalaryId", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Forecast_19_Result>("SP_Forecast_19", sV_SalaryIdParameter, monthParameter);
        }
    
        public virtual ObjectResult<SummaryFA_Result> SummaryFA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SummaryFA_Result>("SummaryFA");
        }
    }
}
