//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EffortEstimationExcelEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScrumTeam
    {
        public int ScrumTeamId { get; set; }
        public string ScrumTeam { get; set; }
    }
}
